# Generated by Django 4.1.7 on 2023-03-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_type', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11)),
            ],
        ),
    ]
